---
title: "EAGER Plants"
author: "Nancy"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)

# Read Fertsyntraitsall
plants <- read.csv("Fertsyntraitsall.csv")

# Select columns
selected_columns_plants <- plants[c('Site','Experiment','Abbreviation','Year', 'block', 'plotID','Species_code','USDA_symbol','Scientific_name', 'FAMILY', 'COT', 'DUR', 'LF', 'DLF', 'HT', 'CLO', 'ORIGIN', 'Variety', 'Notes')]
```

```{r}
# Read Maya plants
maya_plants <- read.csv("Plant-Traits - Sheet4.csv")

# Add new column to Maya plants
maya_plants$Scientific_name <- paste0(
  toupper(substr(maya_plants$genus,1,1)), # Uppercase the first letter of 'genus'
  substr(maya_plants$genus,2, nchar(maya_plants$genus))," ", # Rest of 'genus'
  maya_plants$species
)
```

```{r}
#MERGE THE TWO DATASET
merged_plants <- left_join(maya_plants,selected_columns_plants, by="Scientific_name")
```

```{r}
# Specify the file path where you want to save the CSV file
file_path <- "merged_plants.csv"

# Export the dataframe to a CSV file
write.csv(merged_plants, file = file_path, row.names = FALSE)
```

```{r}
# Remove specific columns
filtered_mergeplants <- merged_plants %>%
  select(-Experiment, -Abbreviation, -Year, -block, -plotID)

# Filter out data for site KNZ
#KNZ_mergeplants <- filtered_mergeplants %>% filter(Site == 'KNZ')

# Keep only distinct species names 
distinct_plants <- filtered_mergeplants %>%
  group_by(Site, Scientific_name) %>%
  distinct() %>%
  ungroup()
distinct_plants <- distinct_plants %>% rename('Height'='HT','detailed_life_form'='DLF','lifeForm'='LF','life_duration'='DUR','cotyledon_num'='COT','clonal_growth_potential'='CLO')

all_plants <- distinct_plants %>% select(-Species_code)

save_file <-"all_plants.csv"

write.csv(all_plants,file=save_file,row.names=FALSE)
```

